### ISSUE TITLE
Setup initial code with linting and pre-commit hooks

### ISSUE THREAD

**Issue by cmplx-xyttmt** [SunbirdAI/sunbird-ai-api-experimental#1]
This task sets up the initial codebase. The following are the tasks that will be involved:
```[tasklist]
### Tasks
- [x] Setup a basic FastAPI application with one endpoint that simply returns "Hello World".
- [x] Setup a virtual environment.
- [x] Setup .gitignore file (https://github.com/github/gitignore/blob/main/Python.gitignore)
- [x] Add a requirements.txt file.
- [x] Add a basic passing test.
- [x] Add a pre-commit hook that runs flake8 and also runs the tests.
```
