### ISSUE TITLE
Setup Github actions and badges

### ISSUE THREAD

**Issue by cmplx-xyttmt** [SunbirdAI/sunbird-ai-api-experimental#2]
This goal of this is to add a Github action that runs the test, reports coverage and add the badges to the README.md file.
```[tasklist]
### Tasks
- [x] Add a Github action that runs the tests automatically
- [x] Add a step that runs flake8
- [x] Add a step that reports coverage
- [x] Add coverage and build badges to the README.md
```

**Comment by ignatius-k** [comment]
The workflow is based on Python 3.9
