### ISSUE TITLE
Implement translation with text input

### ISSUE THREAD

**Issue by cmplx-xyttmt** [SunbirdAI/sunbird-ai-api-experimental#3]
- See the design doc for more details. 
- To use the HuggingFace Inference API appropriately, you may have to implement exponential back-off becuase the model takes some time to load.
- Ensure the endpoint structure follows what's in the design doc.
```[tasklist]
### Tasks
- [x] Add code that does English to multiple translation using the HuggingFace Inference API (Conrad).
- [x] Implement Multiple-to-English translation (Ignatius)
- [x] Implement Local-to-Local translation
- [x] Add language ID for cases when the source language isn't specified.
- [x] Split text longer than 200 characters into chunks.
- [x] Add validation to ensure that input is longer than 3 characters and less than 5000 characters.
- [x] Add tests for this functionality.
```

**Comment by ConradKash** [comment]
Hey @Ignatius-K  I am done with the first task you can clone the branch and implement multiple to english translation
