### ISSUE TITLE
Add a basic frontend that does text translation

### ISSUE THREAD

**Issue by cmplx-xyttmt** [SunbirdAI/sunbird-ai-api-experimental#5]
Create a frontend similar to Sunbird translate or Google translate that supports text input translation.
```[tasklist]
### Tasks
- [ ] Setup Jinja templates and TailwindCSS (optional)
- [ ] Design basic UI with a text area for source language, and text area for the target language and dropdowns for users to select both source and target languages.
- [ ] Implement the translate functionality for this UI.
```
