### ISSUE TITLE
Add file translation support to the frontend

### ISSUE THREAD

**Issue by cmplx-xyttmt** [SunbirdAI/sunbird-ai-api-experimental#6]
Add an option on the frontend that lets users upload a file they want to translate. (Must let them know that only .txt or .pdf files are allowed)
```[tasklist]
### Tasks
- [ ] Add a form with "Upload file to translate" and "Source Language" options to the existing frontend.
- [ ] Form submission should trigger the existing code for file translation.
- [ ] Once the translation is done, the UI should display a button where the user can download the translated file.
```
