### ISSUE TITLE
Deploy the application to the cloud

### ISSUE THREAD

**Issue by cmplx-xyttmt** [SunbirdAI/sunbird-ai-api-experimental#7]
Deploy the application to the cloud.
```[tasklist]
### Tasks
- [ ] Decide on which cloud platform to use (fly.io, heroku or cloud run)
- [ ] Deploy the application
- [ ] Ensure that no security keys are leaked in the soruce code
```
